#  ┬─┐┬─┐┬─┐  ┌─┐┌─┐┌┌┐┌┌┐o┌┐┐
#  │─┘│┬┘├─ ──│  │ ││││││││ │ 
#  ┘  ┘└┘┴─┘  └─┘┘─┘┘ ┘┘ ┘┘ ┘ 

repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.20.0
  hooks:
  - id: gitleaks
    args:
    - --config=gitleaks.toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: regenerate-manifests
      name: Regenerate manifests
      entry: make -C src manifests generate fmt vet
      language: system
      files: src/.+
      types: [file]
      pass_filenames: false
