#  ┬─┐┬─┐┬  ┬─┐┬─┐┐─┐┬─┐
#  │┬┘├─ │  ├─ │─┤└─┐├─ 
#  ┘└┘┴─┘┘─┘┴─┘┘ ┘──┘┴─┘

name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Kustomize Build
        uses: karancode/kustomize-github-action@1.3.2
        with:
          kustomize_version: 5.4.2
          kustomize_build_dir: src/config/default
          kustomize_comment: true
          kustomize_output_file: install.yaml
          enable_alpha_plugins: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: install.yaml
