#  ┬─┐┬─┐┬  ┬─┐┬─┐┐─┐┬─┐
#  │┬┘├─ │  ├─ │─┤└─┐├─ 
#  ┘└┘┴─┘┘─┘┴─┘┘ ┘──┘┴─┘

name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image tag
        uses: mikefarah/yq@v4
        env:
          TEMPLATE: |-
            .images += {
              "name": "ghcr.io/${{ github.repository }}",
              "newTag": "${{ github.ref }}"
            }
        with:
          cmd: yq -i "${TEMPLATE}" src/config/manager/kustomization.yaml

      - name: Kustomize Build
        run: kustomize build src/config/default | tee install.yaml

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: install.yaml
